CREATE TABLE "users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255),
  "email" varchar(255) UNIQUE,
  "email_verified_at" timestamp,
  "password" varchar(255),
  "remember_token" varchar(100),
  "current_team_id" bigint,
  "profile_photo_path" varchar(2048),
  "user_type" enum(admin,manufacturer,client) DEFAULT 'client',
  "status" enum(active,inactive,suspended,pending) DEFAULT 'pending',
  "last_login_at" timestamp,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "permissions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) UNIQUE,
  "guard_name" varchar(255),
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "roles" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) UNIQUE,
  "guard_name" varchar(255),
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "model_has_permissions" (
  "permission_id" bigint,
  "model_type" varchar(255),
  "model_id" bigint,
  PRIMARY KEY ("permission_id", "model_id", "model_type")
);

CREATE TABLE "model_has_roles" (
  "role_id" bigint,
  "model_type" varchar(255),
  "model_id" bigint,
  PRIMARY KEY ("role_id", "model_id", "model_type")
);

CREATE TABLE "role_has_permissions" (
  "permission_id" bigint,
  "role_id" bigint,
  PRIMARY KEY ("permission_id", "role_id")
);

CREATE TABLE "password_reset_tokens" (
  "email" varchar(255) PRIMARY KEY,
  "token" varchar(255),
  "created_at" timestamp
);

CREATE TABLE "sessions" (
  "id" varchar(255) PRIMARY KEY,
  "user_id" bigint,
  "ip_address" varchar(45),
  "user_agent" text,
  "payload" longtext,
  "last_activity" int
);

CREATE TABLE "documents" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "documentable_type" varchar(255),
  "documentable_id" bigint,
  "document_type" enum(kyc_id,business_license,tax_certificate,bank_statement,agreement,invoice,receipt,guarantee,other),
  "title" varchar(255),
  "description" text,
  "file_path" varchar(500),
  "file_name" varchar(255),
  "file_size" bigint,
  "mime_type" varchar(100),
  "document_number" varchar(100),
  "issue_date" date,
  "expiry_date" date,
  "status" enum(pending,approved,rejected,expired) DEFAULT 'pending',
  "uploaded_by" bigint,
  "verified_by" bigint,
  "verified_at" timestamp,
  "remarks" text,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "addresses" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "addressable_type" varchar(255),
  "addressable_id" bigint,
  "address_type" enum(primary,billing,shipping,delivery,warehouse,office,residence) DEFAULT 'primary',
  "label" varchar(100),
  "address_line_1" varchar(500),
  "address_line_2" varchar(500),
  "city" varchar(100),
  "state" varchar(100),
  "postal_code" varchar(20),
  "country" varchar(100) DEFAULT 'Uganda',
  "latitude" decimal(10,8),
  "longitude" decimal(11,8),
  "is_default" boolean DEFAULT false,
  "is_verified" boolean DEFAULT false,
  "verified_at" timestamp,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "comments" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "commentable_type" varchar(255),
  "commentable_id" bigint,
  "user_id" bigint,
  "parent_id" bigint,
  "comment_type" enum(note,status_change,reminder,follow_up,issue,resolution),
  "title" varchar(255),
  "content" text,
  "priority" enum(low,medium,high,urgent) DEFAULT 'medium',
  "is_internal" boolean DEFAULT true,
  "is_pinned" boolean DEFAULT false,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "attachments" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "attachable_type" varchar(255),
  "attachable_id" bigint,
  "file_type" enum(image,document,video,audio,other),
  "title" varchar(255),
  "description" text,
  "file_path" varchar(500),
  "file_name" varchar(255),
  "original_name" varchar(255),
  "file_size" bigint,
  "mime_type" varchar(100),
  "uploaded_by" bigint,
  "is_public" boolean DEFAULT false,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "activity_log" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "log_name" varchar(255),
  "description" text,
  "subject_type" varchar(255),
  "event" varchar(255),
  "subject_id" bigint,
  "causer_type" varchar(255),
  "causer_id" bigint,
  "properties" json,
  "batch_uuid" uuid,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "manufacturers" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint UNIQUE,
  "company_name" varchar(255),
  "company_registration_number" varchar(100) UNIQUE,
  "business_type" enum(sole_proprietorship,partnership,limited_company,corporation),
  "industry" varchar(100),
  "tax_identification_number" varchar(100),
  "website" varchar(255),
  "established_year" int,
  "employee_count_range" enum(1-10,11-50,51-200,201-500,500+),
  "description" text,
  "logo_path" varchar(500),
  "status" enum(pending,active,suspended,inactive) DEFAULT 'pending',
  "verification_status" enum(unverified,under_review,verified,rejected) DEFAULT 'unverified',
  "verified_at" timestamp,
  "verified_by" bigint,
  "commission_rate" decimal(5,2) DEFAULT 0,
  "credit_limit" decimal(15,2) DEFAULT 0,
  "payment_terms" int DEFAULT 30,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "manufacturer_contacts" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "manufacturer_id" bigint,
  "contact_type" enum(primary,secondary,finance,technical,sales),
  "name" varchar(255),
  "title" varchar(100),
  "email" varchar(255),
  "phone" varchar(50),
  "is_primary" boolean DEFAULT false,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "product_categories" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255),
  "slug" varchar(255) UNIQUE,
  "description" text,
  "parent_id" bigint,
  "image_path" varchar(500),
  "is_active" boolean DEFAULT true,
  "sort_order" int DEFAULT 0,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "products" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "manufacturer_id" bigint,
  "category_id" bigint,
  "name" varchar(255),
  "slug" varchar(255),
  "sku" varchar(100) UNIQUE,
  "description" text,
  "specifications" json,
  "unit_price" decimal(15,2),
  "lease_price" decimal(15,2),
  "currency" varchar(3) DEFAULT 'UGX',
  "minimum_lease_duration" int DEFAULT 12,
  "maximum_lease_duration" int DEFAULT 60,
  "warranty_period" int DEFAULT 12,
  "maintenance_required" boolean DEFAULT false,
  "installation_required" boolean DEFAULT true,
  "weight_kg" decimal(8,2),
  "dimensions_cm" varchar(50),
  "color" varchar(50),
  "material" varchar(100),
  "capacity_liters" int,
  "images" json,
  "status" enum(draft,active,inactive,discontinued) DEFAULT 'draft',
  "is_featured" boolean DEFAULT false,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "inventory" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" bigint,
  "location" varchar(255),
  "quantity_available" int DEFAULT 0,
  "quantity_reserved" int DEFAULT 0,
  "quantity_leased" int DEFAULT 0,
  "reorder_level" int DEFAULT 0,
  "last_restocked_at" timestamp,
  "notes" text,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "clients" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint UNIQUE,
  "client_code" varchar(50) UNIQUE,
  "client_type" enum(individual,business,cooperative,ngo),
  "title" "enum(Mr,Mrs,Ms,Dr,Prof)",
  "first_name" varchar(255),
  "middle_name" varchar(255),
  "last_name" varchar(255),
  "business_name" varchar(255),
  "date_of_birth" date,
  "gender" enum(male,female,other),
  "marital_status" enum(single,married,divorced,widowed),
  "id_type" enum(national_id,passport,driving_license),
  "id_number" varchar(100) UNIQUE,
  "phone_primary" varchar(50),
  "phone_secondary" varchar(50),
  "email_secondary" varchar(255),
  "occupation" varchar(100),
  "employer" varchar(255),
  "monthly_income" decimal(15,2),
  "bank_name" varchar(100),
  "bank_account_number" varchar(50),
  "mobile_money_provider" varchar(50),
  "mobile_money_number" varchar(50),
  "preferred_payment_method" enum(bank_transfer,mobile_money,cash,cheque) DEFAULT 'mobile_money',
  "kyc_status" enum(incomplete,pending,approved,rejected) DEFAULT 'incomplete',
  "kyc_completed_at" timestamp,
  "credit_score" int,
  "risk_rating" enum(low,medium,high),
  "status" enum(active,inactive,blacklisted,suspended) DEFAULT 'active',
  "registration_source" enum(online,agent,walk_in,referral),
  "referred_by" bigint,
  "notes" text,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "client_references" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "client_id" bigint,
  "reference_type" enum(personal,professional,family,neighbor,business),
  "name" varchar(255),
  "relationship" varchar(100),
  "phone" varchar(50),
  "email" varchar(255),
  "address" text,
  "occupation" varchar(100),
  "years_known" int,
  "is_contacted" boolean DEFAULT false,
  "contact_notes" text,
  "verification_status" enum(pending,verified,failed) DEFAULT 'pending',
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "client_dependents" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "client_id" bigint,
  "name" varchar(255),
  "relationship" varchar(50),
  "age" int,
  "is_employed" boolean DEFAULT false,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "lease_applications" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "application_number" varchar(50) UNIQUE,
  "client_id" bigint,
  "product_id" bigint,
  "quantity" int DEFAULT 1,
  "lease_duration_months" int,
  "monthly_payment" decimal(15,2),
  "total_lease_amount" decimal(15,2),
  "down_payment" decimal(15,2) DEFAULT 0,
  "security_deposit" decimal(15,2) DEFAULT 0,
  "application_fee" decimal(15,2) DEFAULT 0,
  "delivery_address" text,
  "preferred_delivery_date" date,
  "purpose_of_lease" text,
  "collateral_description" text,
  "guarantor_required" boolean DEFAULT false,
  "employment_verification" boolean DEFAULT false,
  "income_verification" boolean DEFAULT false,
  "status" enum(draft,submitted,under_review,approved,rejected,cancelled) DEFAULT 'draft',
  "risk_assessment_score" decimal(5,2),
  "assessment_notes" text,
  "submitted_at" timestamp,
  "reviewed_at" timestamp,
  "reviewed_by" bigint,
  "approval_notes" text,
  "rejection_reason" text,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "guarantors" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "lease_application_id" bigint,
  "name" varchar(255),
  "id_type" enum(national_id,passport,driving_license),
  "id_number" varchar(100),
  "phone" varchar(50),
  "email" varchar(255),
  "occupation" varchar(100),
  "employer" varchar(255),
  "monthly_income" decimal(15,2),
  "relationship_to_client" varchar(100),
  "guarantee_amount" decimal(15,2),
  "consent_given" boolean DEFAULT false,
  "consent_date" timestamp,
  "verification_status" enum(pending,verified,rejected) DEFAULT 'pending',
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "lease_agreements" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "agreement_number" varchar(50) UNIQUE,
  "lease_application_id" bigint UNIQUE,
  "client_id" bigint,
  "product_id" bigint,
  "manufacturer_id" bigint,
  "quantity" int,
  "lease_start_date" date,
  "lease_end_date" date,
  "lease_duration_months" int,
  "monthly_payment" decimal(15,2),
  "total_lease_amount" decimal(15,2),
  "down_payment" decimal(15,2),
  "security_deposit" decimal(15,2),
  "late_fee_percentage" decimal(5,2) DEFAULT 5,
  "grace_period_days" int DEFAULT 5,
  "early_termination_fee" decimal(15,2),
  "maintenance_responsibility" enum(client,manufacturer,shared) DEFAULT 'client',
  "insurance_required" boolean DEFAULT false,
  "insurance_provider" varchar(255),
  "terms_and_conditions" text,
  "special_terms" text,
  "status" enum(draft,active,completed,terminated,breached) DEFAULT 'draft',
  "signed_by_client" boolean DEFAULT false,
  "signed_by_manufacturer" boolean DEFAULT false,
  "client_signature_date" timestamp,
  "manufacturer_signature_date" timestamp,
  "witness_name" varchar(255),
  "witness_signature_date" timestamp,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "payment_schedules" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "lease_agreement_id" bigint,
  "installment_number" int,
  "due_date" date,
  "principal_amount" decimal(15,2),
  "interest_amount" decimal(15,2) DEFAULT 0,
  "total_amount" decimal(15,2),
  "status" enum(pending,paid,partial,overdue,waived) DEFAULT 'pending',
  "paid_amount" decimal(15,2) DEFAULT 0,
  "paid_date" date,
  "late_fee" decimal(15,2) DEFAULT 0,
  "notes" text,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "payments" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "payment_reference" varchar(100) UNIQUE,
  "lease_agreement_id" bigint,
  "payment_schedule_id" bigint,
  "client_id" bigint,
  "payment_type" enum(down_payment,installment,late_fee,security_deposit,early_termination,other),
  "amount" decimal(15,2),
  "currency" varchar(3) DEFAULT 'UGX',
  "payment_method" enum(cash,bank_transfer,mobile_money,cheque,card),
  "payment_channel" varchar(100),
  "transaction_reference" varchar(255),
  "external_reference" varchar(255),
  "payment_date" date,
  "due_date" date,
  "status" enum(pending,processing,completed,failed,cancelled,refunded) DEFAULT 'pending',
  "processing_fee" decimal(10,2) DEFAULT 0,
  "net_amount" decimal(15,2),
  "confirmation_code" varchar(100),
  "receipt_number" varchar(100),
  "notes" text,
  "processed_by" bigint,
  "processed_at" timestamp,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "payment_methods" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "client_id" bigint,
  "method_type" enum(bank_account,mobile_money,card),
  "provider" varchar(100),
  "account_number" varchar(100),
  "account_name" varchar(255),
  "is_default" boolean DEFAULT false,
  "is_verified" boolean DEFAULT false,
  "status" enum(active,inactive,blocked) DEFAULT 'active',
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "commissions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "manufacturer_id" bigint,
  "lease_agreement_id" bigint,
  "payment_id" bigint,
  "commission_type" enum(lease_commission,maintenance_commission,bonus),
  "base_amount" decimal(15,2),
  "commission_rate" decimal(5,2),
  "commission_amount" decimal(15,2),
  "currency" varchar(3) DEFAULT 'UGX',
  "status" enum(pending,approved,paid,cancelled) DEFAULT 'pending',
  "calculation_date" date,
  "due_date" date,
  "paid_date" date,
  "payment_reference" varchar(255),
  "notes" text,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "accounts" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "account_code" varchar(20) UNIQUE,
  "account_name" varchar(255),
  "account_type" enum(asset,liability,equity,income,expense),
  "parent_id" bigint,
  "balance" decimal(15,2) DEFAULT 0,
  "is_active" boolean DEFAULT true,
  "description" text,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "journal_entries" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "entry_number" varchar(50) UNIQUE,
  "transaction_date" date,
  "reference_type" varchar(255),
  "reference_id" bigint,
  "description" text,
  "total_debit" decimal(15,2),
  "total_credit" decimal(15,2),
  "status" enum(draft,posted,reversed) DEFAULT 'draft',
  "created_by" bigint,
  "posted_by" bigint,
  "posted_at" timestamp,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "journal_entry_lines" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "journal_entry_id" bigint,
  "account_id" bigint,
  "description" text,
  "debit_amount" decimal(15,2) DEFAULT 0,
  "credit_amount" decimal(15,2) DEFAULT 0,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "notification_templates" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) UNIQUE,
  "type" enum(email,sms,push,system),
  "event_trigger" varchar(255),
  "subject" varchar(500),
  "content" text,
  "variables" json,
  "is_active" boolean DEFAULT true,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "notifications" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "type" enum(email,sms,push,system),
  "notifiable_type" varchar(255),
  "notifiable_id" bigint,
  "data" json,
  "read_at" timestamp,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "messages" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sender_id" bigint,
  "recipient_id" bigint,
  "subject" varchar(500),
  "body" text,
  "message_type" enum(system,user,automated),
  "priority" enum(low,normal,high,urgent) DEFAULT 'normal',
  "status" enum(draft,sent,delivered,read,failed) DEFAULT 'draft',
  "read_at" timestamp,
  "parent_id" bigint,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "sms_logs" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "recipient" varchar(50),
  "message" text,
  "status" enum(pending,sent,delivered,failed),
  "provider" varchar(100),
  "external_id" varchar(255),
  "cost" decimal(8,4),
  "error_message" text,
  "sent_at" timestamp,
  "delivered_at" timestamp,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "email_logs" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "recipient" varchar(255),
  "subject" varchar(500),
  "body" text,
  "status" enum(pending,sent,delivered,failed,bounced),
  "provider" varchar(100),
  "external_id" varchar(255),
  "error_message" text,
  "sent_at" timestamp,
  "delivered_at" timestamp,
  "opened_at" timestamp,
  "clicked_at" timestamp,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "reports" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255),
  "description" text,
  "report_type" enum(financial,operational,client,manufacturer,custom),
  "parameters" json,
  "schedule_frequency" enum(once,daily,weekly,monthly,quarterly,yearly),
  "next_run_at" timestamp,
  "last_run_at" timestamp,
  "is_active" boolean DEFAULT true,
  "created_by" bigint,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "report_executions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "report_id" bigint,
  "status" enum(pending,running,completed,failed),
  "file_path" varchar(500),
  "file_size" bigint,
  "execution_time_seconds" int,
  "error_message" text,
  "parameters_used" json,
  "executed_by" bigint,
  "started_at" timestamp,
  "completed_at" timestamp,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "analytics_events" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "event_name" varchar(255),
  "event_type" enum(page_view,user_action,system_event,business_metric),
  "user_id" bigint,
  "session_id" varchar(255),
  "properties" json,
  "metadata" json,
  "ip_address" varchar(45),
  "user_agent" text,
  "occurred_at" timestamp DEFAULT (now()),
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "settings" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "key" varchar(255) UNIQUE,
  "value" text,
  "type" enum(string,integer,decimal,boolean,json),
  "group_name" varchar(100),
  "description" text,
  "is_public" boolean DEFAULT false,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "currencies" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(3) UNIQUE,
  "name" varchar(255),
  "symbol" varchar(10),
  "exchange_rate" decimal(10,4) DEFAULT 1,
  "is_default" boolean DEFAULT false,
  "is_active" boolean DEFAULT true,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "audit_trails" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint,
  "action" varchar(255),
  "auditable_type" varchar(255),
  "auditable_id" bigint,
  "old_values" json,
  "new_values" json,
  "url" varchar(500),
  "ip_address" varchar(45),
  "user_agent" text,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "system_logs" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "level" enum(emergency,alert,critical,error,warning,notice,info,debug),
  "message" text,
  "context" json,
  "channel" varchar(255),
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "maintenance_schedules" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "lease_agreement_id" bigint,
  "maintenance_type" enum(routine,preventive,corrective,emergency),
  "description" text,
  "scheduled_date" date,
  "frequency_months" int,
  "estimated_cost" decimal(10,2),
  "actual_cost" decimal(10,2),
  "status" enum(scheduled,in_progress,completed,cancelled,overdue) DEFAULT 'scheduled',
  "assigned_to" varchar(255),
  "completion_date" date,
  "notes" text,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "insurance_policies" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "lease_agreement_id" bigint,
  "policy_number" varchar(100) UNIQUE,
  "insurance_provider" varchar(255),
  "policy_type" enum(comprehensive,third_party,fire_theft),
  "coverage_amount" decimal(15,2),
  "premium_amount" decimal(10,2),
  "start_date" date,
  "end_date" date,
  "status" enum(active,expired,cancelled) DEFAULT 'active',
  "beneficiary" varchar(255),
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "late_payment_notices" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "payment_schedule_id" bigint,
  "lease_agreement_id" bigint,
  "client_id" bigint,
  "notice_type" enum(reminder,first_notice,second_notice,final_notice,legal_notice),
  "days_overdue" int,
  "outstanding_amount" decimal(15,2),
  "late_fee_charged" decimal(10,2) DEFAULT 0,
  "notice_date" date,
  "response_due_date" date,
  "status" enum(sent,acknowledged,resolved,escalated) DEFAULT 'sent',
  "delivery_method" enum(sms,email,physical,phone_call),
  "sent_by" bigint,
  "acknowledged_at" timestamp,
  "resolved_at" timestamp,
  "notes" text,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "credit_assessments" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "client_id" bigint,
  "lease_application_id" bigint,
  "assessment_type" enum(initial,periodic,special),
  "credit_score" int,
  "risk_rating" enum(low,medium,high,very_high),
  "income_verification_status" enum(verified,partial,unverified),
  "employment_verification_status" enum(verified,partial,unverified),
  "debt_to_income_ratio" decimal(5,2),
  "payment_history_score" int,
  "recommended_credit_limit" decimal(15,2),
  "assessment_notes" text,
  "assessed_by" bigint,
  "assessment_date" date,
  "valid_until" date,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "marketing_campaigns" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255),
  "description" text,
  "campaign_type" enum(sms,email,social_media,print,radio,tv,online),
  "target_audience" json,
  "budget" decimal(10,2),
  "start_date" date,
  "end_date" date,
  "status" enum(draft,active,paused,completed,cancelled) DEFAULT 'draft',
  "created_by" bigint,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "campaign_responses" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "campaign_id" bigint,
  "client_id" bigint,
  "response_type" enum(view,click,inquiry,application,conversion),
  "response_date" timestamp DEFAULT (now()),
  "source_channel" varchar(100),
  "metadata" json,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "dashboard_metrics" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "metric_name" varchar(255),
  "metric_value" decimal(15,2),
  "metric_type" enum(count,sum,average,percentage,ratio),
  "period_type" enum(daily,weekly,monthly,quarterly,yearly),
  "period_start" date,
  "period_end" date,
  "metadata" json,
  "created_at" timestamp DEFAULT (now())
);

CREATE INDEX ON "model_has_permissions" ("model_id", "model_type");

CREATE INDEX ON "model_has_roles" ("model_id", "model_type");

CREATE INDEX ON "sessions" ("user_id");

CREATE INDEX ON "sessions" ("last_activity");

CREATE INDEX ON "documents" ("documentable_type", "documentable_id");

CREATE INDEX ON "documents" ("document_type");

CREATE INDEX ON "documents" ("status");

CREATE INDEX ON "addresses" ("addressable_type", "addressable_id");

CREATE INDEX ON "addresses" ("address_type");

CREATE INDEX ON "addresses" ("city");

CREATE INDEX ON "addresses" ("state");

CREATE INDEX ON "comments" ("commentable_type", "commentable_id");

CREATE INDEX ON "comments" ("user_id");

CREATE INDEX ON "comments" ("comment_type");

CREATE INDEX ON "comments" ("created_at");

CREATE INDEX ON "attachments" ("attachable_type", "attachable_id");

CREATE INDEX ON "attachments" ("file_type");

CREATE INDEX ON "attachments" ("uploaded_by");

CREATE INDEX ON "activity_log" ("subject_type", "subject_id");

CREATE INDEX ON "activity_log" ("causer_type", "causer_id");

CREATE INDEX ON "activity_log" ("log_name");

CREATE INDEX ON "activity_log" ("created_at");

CREATE INDEX ON "manufacturers" ("status");

CREATE INDEX ON "manufacturers" ("verification_status");

CREATE INDEX ON "manufacturers" ("company_name");

CREATE INDEX ON "products" ("manufacturer_id");

CREATE INDEX ON "products" ("category_id");

CREATE INDEX ON "products" ("status");

CREATE INDEX ON "products" ("sku");

CREATE INDEX ON "inventory" ("product_id");

CREATE INDEX ON "inventory" ("quantity_available");

CREATE INDEX ON "clients" ("client_code");

CREATE INDEX ON "clients" ("id_number");

CREATE INDEX ON "clients" ("kyc_status");

CREATE INDEX ON "clients" ("status");

CREATE INDEX ON "clients" ("phone_primary");

CREATE INDEX ON "lease_applications" ("application_number");

CREATE INDEX ON "lease_applications" ("client_id");

CREATE INDEX ON "lease_applications" ("status");

CREATE INDEX ON "lease_applications" ("submitted_at");

CREATE INDEX ON "lease_agreements" ("agreement_number");

CREATE INDEX ON "lease_agreements" ("client_id");

CREATE INDEX ON "lease_agreements" ("status");

CREATE INDEX ON "lease_agreements" ("lease_start_date");

CREATE INDEX ON "lease_agreements" ("lease_end_date");

CREATE UNIQUE INDEX ON "payment_schedules" ("lease_agreement_id", "installment_number");

CREATE INDEX ON "payment_schedules" ("due_date");

CREATE INDEX ON "payment_schedules" ("status");

CREATE INDEX ON "payments" ("payment_reference");

CREATE INDEX ON "payments" ("lease_agreement_id");

CREATE INDEX ON "payments" ("client_id");

CREATE INDEX ON "payments" ("payment_date");

CREATE INDEX ON "payments" ("status");

CREATE INDEX ON "commissions" ("manufacturer_id");

CREATE INDEX ON "commissions" ("lease_agreement_id");

CREATE INDEX ON "commissions" ("status");

CREATE INDEX ON "commissions" ("due_date");

CREATE INDEX ON "journal_entries" ("entry_number");

CREATE INDEX ON "journal_entries" ("transaction_date");

CREATE INDEX ON "journal_entries" ("reference_type", "reference_id");

CREATE INDEX ON "journal_entries" ("status");

CREATE INDEX ON "notifications" ("notifiable_type", "notifiable_id");

CREATE INDEX ON "notifications" ("read_at");

CREATE INDEX ON "notifications" ("created_at");

CREATE INDEX ON "messages" ("sender_id");

CREATE INDEX ON "messages" ("recipient_id");

CREATE INDEX ON "messages" ("status");

CREATE INDEX ON "messages" ("created_at");

CREATE INDEX ON "sms_logs" ("recipient");

CREATE INDEX ON "sms_logs" ("status");

CREATE INDEX ON "sms_logs" ("sent_at");

CREATE INDEX ON "email_logs" ("recipient");

CREATE INDEX ON "email_logs" ("status");

CREATE INDEX ON "email_logs" ("sent_at");

CREATE INDEX ON "report_executions" ("report_id");

CREATE INDEX ON "report_executions" ("status");

CREATE INDEX ON "report_executions" ("created_at");

CREATE INDEX ON "analytics_events" ("event_name");

CREATE INDEX ON "analytics_events" ("event_type");

CREATE INDEX ON "analytics_events" ("user_id");

CREATE INDEX ON "analytics_events" ("occurred_at");

CREATE INDEX ON "audit_trails" ("user_id");

CREATE INDEX ON "audit_trails" ("auditable_type", "auditable_id");

CREATE INDEX ON "audit_trails" ("action");

CREATE INDEX ON "audit_trails" ("created_at");

CREATE INDEX ON "system_logs" ("level");

CREATE INDEX ON "system_logs" ("channel");

CREATE INDEX ON "system_logs" ("created_at");

CREATE INDEX ON "maintenance_schedules" ("lease_agreement_id");

CREATE INDEX ON "maintenance_schedules" ("scheduled_date");

CREATE INDEX ON "maintenance_schedules" ("status");

CREATE INDEX ON "insurance_policies" ("lease_agreement_id");

CREATE INDEX ON "insurance_policies" ("policy_number");

CREATE INDEX ON "insurance_policies" ("status");

CREATE INDEX ON "insurance_policies" ("end_date");

CREATE INDEX ON "late_payment_notices" ("payment_schedule_id");

CREATE INDEX ON "late_payment_notices" ("client_id");

CREATE INDEX ON "late_payment_notices" ("status");

CREATE INDEX ON "late_payment_notices" ("notice_date");

CREATE INDEX ON "credit_assessments" ("client_id");

CREATE INDEX ON "credit_assessments" ("assessment_date");

CREATE INDEX ON "credit_assessments" ("risk_rating");

CREATE INDEX ON "campaign_responses" ("campaign_id");

CREATE INDEX ON "campaign_responses" ("client_id");

CREATE INDEX ON "campaign_responses" ("response_type");

CREATE INDEX ON "campaign_responses" ("response_date");

CREATE UNIQUE INDEX ON "dashboard_metrics" ("metric_name", "period_start", "period_end");

CREATE INDEX ON "dashboard_metrics" ("period_type");

ALTER TABLE "model_has_permissions" ADD FOREIGN KEY ("permission_id") REFERENCES "permissions" ("id");

ALTER TABLE "model_has_roles" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id");

ALTER TABLE "role_has_permissions" ADD FOREIGN KEY ("permission_id") REFERENCES "permissions" ("id");

ALTER TABLE "role_has_permissions" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id");

ALTER TABLE "sessions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "documents" ADD FOREIGN KEY ("uploaded_by") REFERENCES "users" ("id");

ALTER TABLE "documents" ADD FOREIGN KEY ("verified_by") REFERENCES "users" ("id");

ALTER TABLE "comments" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "comments" ADD FOREIGN KEY ("parent_id") REFERENCES "comments" ("id");

ALTER TABLE "attachments" ADD FOREIGN KEY ("uploaded_by") REFERENCES "users" ("id");

ALTER TABLE "manufacturers" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "manufacturers" ADD FOREIGN KEY ("verified_by") REFERENCES "users" ("id");

ALTER TABLE "manufacturer_contacts" ADD FOREIGN KEY ("manufacturer_id") REFERENCES "manufacturers" ("id");

ALTER TABLE "product_categories" ADD FOREIGN KEY ("parent_id") REFERENCES "product_categories" ("id");

ALTER TABLE "products" ADD FOREIGN KEY ("manufacturer_id") REFERENCES "manufacturers" ("id");

ALTER TABLE "products" ADD FOREIGN KEY ("category_id") REFERENCES "product_categories" ("id");

ALTER TABLE "inventory" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");

ALTER TABLE "clients" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "clients" ADD FOREIGN KEY ("referred_by") REFERENCES "clients" ("id");

ALTER TABLE "client_references" ADD FOREIGN KEY ("client_id") REFERENCES "clients" ("id");

ALTER TABLE "client_dependents" ADD FOREIGN KEY ("client_id") REFERENCES "clients" ("id");

ALTER TABLE "lease_applications" ADD FOREIGN KEY ("client_id") REFERENCES "clients" ("id");

ALTER TABLE "lease_applications" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");

ALTER TABLE "lease_applications" ADD FOREIGN KEY ("reviewed_by") REFERENCES "users" ("id");

ALTER TABLE "guarantors" ADD FOREIGN KEY ("lease_application_id") REFERENCES "lease_applications" ("id");

ALTER TABLE "lease_agreements" ADD FOREIGN KEY ("lease_application_id") REFERENCES "lease_applications" ("id");

ALTER TABLE "lease_agreements" ADD FOREIGN KEY ("client_id") REFERENCES "clients" ("id");

ALTER TABLE "lease_agreements" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");

ALTER TABLE "lease_agreements" ADD FOREIGN KEY ("manufacturer_id") REFERENCES "manufacturers" ("id");

ALTER TABLE "payment_schedules" ADD FOREIGN KEY ("lease_agreement_id") REFERENCES "lease_agreements" ("id");

ALTER TABLE "payments" ADD FOREIGN KEY ("lease_agreement_id") REFERENCES "lease_agreements" ("id");

ALTER TABLE "payments" ADD FOREIGN KEY ("payment_schedule_id") REFERENCES "payment_schedules" ("id");

ALTER TABLE "payments" ADD FOREIGN KEY ("client_id") REFERENCES "clients" ("id");

ALTER TABLE "payments" ADD FOREIGN KEY ("processed_by") REFERENCES "users" ("id");

ALTER TABLE "payment_methods" ADD FOREIGN KEY ("client_id") REFERENCES "clients" ("id");

ALTER TABLE "commissions" ADD FOREIGN KEY ("manufacturer_id") REFERENCES "manufacturers" ("id");

ALTER TABLE "commissions" ADD FOREIGN KEY ("lease_agreement_id") REFERENCES "lease_agreements" ("id");

ALTER TABLE "commissions" ADD FOREIGN KEY ("payment_id") REFERENCES "payments" ("id");

ALTER TABLE "accounts" ADD FOREIGN KEY ("parent_id") REFERENCES "accounts" ("id");

ALTER TABLE "journal_entries" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id");

ALTER TABLE "journal_entries" ADD FOREIGN KEY ("posted_by") REFERENCES "users" ("id");

ALTER TABLE "journal_entry_lines" ADD FOREIGN KEY ("journal_entry_id") REFERENCES "journal_entries" ("id");

ALTER TABLE "journal_entry_lines" ADD FOREIGN KEY ("account_id") REFERENCES "accounts" ("id");

ALTER TABLE "messages" ADD FOREIGN KEY ("sender_id") REFERENCES "users" ("id");

ALTER TABLE "messages" ADD FOREIGN KEY ("recipient_id") REFERENCES "users" ("id");

ALTER TABLE "messages" ADD FOREIGN KEY ("parent_id") REFERENCES "messages" ("id");

ALTER TABLE "reports" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id");

ALTER TABLE "report_executions" ADD FOREIGN KEY ("report_id") REFERENCES "reports" ("id");

ALTER TABLE "report_executions" ADD FOREIGN KEY ("executed_by") REFERENCES "users" ("id");

ALTER TABLE "analytics_events" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "audit_trails" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "maintenance_schedules" ADD FOREIGN KEY ("lease_agreement_id") REFERENCES "lease_agreements" ("id");

ALTER TABLE "insurance_policies" ADD FOREIGN KEY ("lease_agreement_id") REFERENCES "lease_agreements" ("id");

ALTER TABLE "late_payment_notices" ADD FOREIGN KEY ("payment_schedule_id") REFERENCES "payment_schedules" ("id");

ALTER TABLE "late_payment_notices" ADD FOREIGN KEY ("lease_agreement_id") REFERENCES "lease_agreements" ("id");

ALTER TABLE "late_payment_notices" ADD FOREIGN KEY ("client_id") REFERENCES "clients" ("id");

ALTER TABLE "late_payment_notices" ADD FOREIGN KEY ("sent_by") REFERENCES "users" ("id");

ALTER TABLE "credit_assessments" ADD FOREIGN KEY ("client_id") REFERENCES "clients" ("id");

ALTER TABLE "credit_assessments" ADD FOREIGN KEY ("lease_application_id") REFERENCES "lease_applications" ("id");

ALTER TABLE "credit_assessments" ADD FOREIGN KEY ("assessed_by") REFERENCES "users" ("id");

ALTER TABLE "marketing_campaigns" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id");

ALTER TABLE "campaign_responses" ADD FOREIGN KEY ("campaign_id") REFERENCES "marketing_campaigns" ("id");

ALTER TABLE "campaign_responses" ADD FOREIGN KEY ("client_id") REFERENCES "clients" ("id");
